/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.star

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.github.star.greeting' plugin.
 */
class AndroidBuildPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.github.star.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
